chore: Try junit test reporting

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -74,7 +74,14 @@ jobs:
 
       - name: Run functional tests
         working-directory: label_studio
-        run: poetry run pytest -vv -n auto
+        run: poetry run pytest -vv -n auto --junit-xml=pytest-junit.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: './label_studio/pytest-junit.xml'
+          annotate_only: true
 
   run_pytest_postgresql:
     name: LS PostgreSQL Ubuntu
@@ -159,7 +166,14 @@ jobs:
 
       - name: Run functional tests
         working-directory: label_studio
-        run: poetry run pytest --cov=. --cov-report=xml -vv -n auto
+        run: poetry run pytest --cov=. --cov-report=xml -vv -n auto --junit-xml=pytest-junit.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: './label_studio/pytest-junit.xml'
+          annotate_only: true
 
       - name: Upload coverage to Codecov
         if: ${{ github.event.pull_request.head.repo.fork == false && github.event.pull_request.user.login != 'dependabot[bot]' }}
@@ -232,4 +246,11 @@ jobs:
         env:
           COLLECT_ANALYTICS: 0
         working-directory: label_studio
-        run: poetry run pytest -vv -n auto
+        run: poetry run pytest -vv -n auto --junit-xml=pytest-junit.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: './label_studio/pytest-junit.xml'
+          annotate_only: true
